---
galaxy_info:
  author: Leif Madsen
  description: SA Telemetry System
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies: []
