{
 "title": "Cloud Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "exported_instances",
    "label": "Cloud Nodes",
    "query": "label_values(exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sa_collectd_uptime{exported_instance=\"$exported_instances\"}"
    }
   ]
  },
  {
   "title": "Short Term Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sa_collectd_load_shortterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Mid Term Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sa_collectd_load_midterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Long Term Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sa_collectd_load_longterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_memory{exported_instance=\"$exported_instances\"}[5m])",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "Packets Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_interface_if_packets_rx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "RX interface {{interface}}"
    },
    {
     "expr": "rate(sa_collectd_interface_if_packets_tx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "TX interface {{interface}}"
    }
   ]
  },
  {
   "title": "Disk Time Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_disk_disk_io_time_io_time_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "disk {{disk}}"
    }
   ]
  },
  {
   "title": "Interface Errors Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_interface_if_errors_rx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "RX interface {{interface}}"
    },
    {
     "expr": "rate(sa_collectd_interface_if_errors_tx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "TX interface {{interface}}"
    }
   ]
  }
 ]
}