---
- name: SA Telemetry Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Telemetry install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_sa_telemetry:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: SA Telemetry
  hosts: oo_first_master
  tasks:
    - include_vars:
        file: dashboards.yml

    - import_role:
        name: sa_telemetry

- name: SA Telemetry Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set SA Telemetry install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_sa_telemetry:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
